# FLIR Camera Configuration

left:
  PixelFormat: Mono16
  DigitalOutput: 3 
  GrbCh0TrigCfgFrameToSkip: 0
  SensorGainMode: 1  ### 1:lowGain 2:highGain
  Gain: 1
  GevSCPSPacketSize: 1500

right:
  PixelFormat: Mono16
  DigitalOutput: 3 
  GrbCh0TrigCfgFrameToSkip: 0
  SensorGainMode: 2  ### 1:lowGain 2:highGain
  Gain: 2
  GevSCPSPacketSize: 1500
